### ISSUE TITLE
An error has occurred.

### ISSUE THREAD

**Issue by CreepercraftYT** [Hipnosis183/TTX-Monitor#2]
when i try to execute TTX-Loader.exe. i get an error message, what can this be?
![image](https://github.com/Hipnosis183/TTX-Monitor/assets/69971786/2f5fafe9-382f-4862-baf1-f828eba2eca8)

**Comment by Hipnosis183** [comment]
More information would be helpful, like what game are you trying to run and what the folder and files look like.

Looking at the loader code it seems that it's an issue with the process creation or dll injection. Make sure you have the loader's dll file (`TTX-Monitor.dll`), and that the game executable is named `game.exe`; otherwise run the loader with the file name as a parameter (`TTX-Loader.exe file-name.exe`)

**Comment by CreepercraftYT** [comment]
the game i'm trying to run is Tetris The Grand Master 3, if it helps: my graphics card is an intel hd graphics 4000.
i have the loader's .dll file, i have put the game's folder inside the loader's folder

**Comment by Hipnosis183** [comment]
Just tested the loader with a clean copy of TGM3 and it just works, even without prior configuration. With a clean dump plus the loader, the directory should look like this:

![screen](https://github.com/Hipnosis183/TTX-Monitor/assets/15963356/d39f0376-723a-483c-a444-0b0624d3feff)

If the problem persists then it's a problem on your end, since, as I explained before, there is nothing else in the loader's code other than the dll injection and process creation.

**Comment by CreepercraftYT** [comment]
ok, the loader doesn't give an error anymore, but the game still won't run because my graphics card is incompatible, i thought that maybe with an intermediary it will work but no.


anyways, thanks ;D
